### ISSUE TITLE
Get 'Failed' message, but working

### ISSUE THREAD

**Issue by 2silver** [collective/collective.quickupload#43]
Try'd in Root or in Folder, with one or multiple files, change title or not, always the same message.

c.quickupload 1.6.2
Plone 4.3.2 (4307)
CMF 2.2.7
Zope 2.13.21
Python 2.7.6 (default, Dec 3 2013, 11:35:01) [GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.2.79)]
PIL 1.7.8 (Pillow)

Log:  
```
2014-02-06 15:22:07 INFO collective.quickupload uploading file with XHR : filename=1968_dodge_charger-wallpaper-2560x1600.jpg, title=, description=, content_type=image/jpeg, portal_type=Image
2014-02-06 15:22:07 INFO collective.quickupload file url: http://localhost:8080/Plone/de/1968-dodge-charger-wallpaper-2560x1600.jpg
```

**Comment by fabiosko** [comment]
I've the same problem... Plone version 4.3.7
Please fix it

**Comment by puittenbroek** [comment]
Are you using plone.protect? Could be related to #53

**Comment by frisi** [comment]
@fabiosko you most probably ran into the issue #52 

as @peterjacobs points out the diazo styling issue was due to the wrong content-type header. 
the only drawback: you still get failed uploads for IE9 since it does not handle `content-type:application/json` correctly

release 1.8.1 should fix this issue. if you still experience problems please re-open
